In [2]:
import torch
import numpy as np

In [3]:
print(torch.cuda.is_available())

True


In [4]:
x = torch.empty(2)
x

tensor([1.9394e-26, 2.0067e-42])

In [7]:
x = torch.rand(2,3)
print(x)
x.dtype

tensor([[0.4238, 0.7476, 0.6695],
        [0.4472, 0.2100, 0.6173]])


torch.float32

In [8]:
y = torch.rand(2,3)
y

tensor([[0.0610, 0.4407, 0.4450],
        [0.9779, 0.3102, 0.0028]])

In [9]:
z = x + y
z

tensor([[0.4848, 1.1883, 1.1144],
        [1.4250, 0.5202, 0.6201]])

In [10]:
z = x - y
z

tensor([[ 0.3629,  0.3068,  0.2245],
        [-0.5307, -0.1002,  0.6144]])

In [11]:
z = x * y
z

tensor([[0.0258, 0.3295, 0.2979],
        [0.4373, 0.0651, 0.0017]])

In [12]:
z = x / y
z

tensor([[  6.9526,   1.6962,   1.5046],
        [  0.4573,   0.6770, 217.8808]])

In [13]:
x = torch.rand(4,4)
x

tensor([[0.1040, 0.1578, 0.7949, 0.7635],
        [0.4396, 0.5538, 0.1376, 0.1634],
        [0.3924, 0.5012, 0.8190, 0.4855],
        [0.5904, 0.4309, 0.3130, 0.5003]])

In [14]:
y = x.view(16)
y

tensor([0.1040, 0.1578, 0.7949, 0.7635, 0.4396, 0.5538, 0.1376, 0.1634, 0.3924,
        0.5012, 0.8190, 0.4855, 0.5904, 0.4309, 0.3130, 0.5003])

In [15]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [16]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)