In [15]:
import torch

In [16]:
x = torch.randn(3, requires_grad=True)
x

tensor([-1.0380, -0.0168,  1.2614], requires_grad=True)

In [17]:
y = x+2
y

tensor([0.9620, 1.9832, 3.2614], grad_fn=<AddBackward0>)

In [18]:
z = y*y*2
z

tensor([ 1.8508,  7.8665, 21.2728], grad_fn=<MulBackward0>)

In [19]:
z.mean().backward()
x.grad

tensor([1.2827, 2.6443, 4.3485])

In [21]:
x.requires_grad_(False)
x.detach()

tensor([-1.0380, -0.0168,  1.2614])

In [23]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(2):
    model_out = (weights*3).sum()
    model_out.backward()

    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
