In [30]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [31]:
class WineDataset(Dataset):
    def __init__(self):
        xy = np.loadtxt('data\\wine.csv', delimiter=",", dtype=np.float32,skiprows=1)
        self.x = torch.from_numpy(xy[:, 1:])
        self.y = torch.from_numpy(xy[:, [0]])
        self.n_samples = xy.shape[0]

    def __getitem__(self, index):
        return self.x[index], self.y[index]

    def __len__(self):
        return self.n_samples

In [32]:
dataset = WineDataset()
first_data = dataset[0]
features, labels = first_data
print(features,labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [33]:
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True)

In [34]:
dataiter = iter(dataloader)
data = next(dataiter)
features, labels = data

In [35]:
features[0], labels[0]

(tensor([1.3710e+01, 1.8600e+00, 2.3600e+00, 1.6600e+01, 1.0100e+02, 2.6100e+00,
         2.8800e+00, 2.7000e-01, 1.6900e+00, 3.8000e+00, 1.1100e+00, 4.0000e+00,
         1.0350e+03]),
 tensor([1.]))

In [36]:
num_epochs = 2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples / 4)

In [37]:
for epoch in range(num_epochs):
    for i, (inputs, labels) in enumerate(dataloader):
        if i % 5 == 0:
            print(f"epoch -> {epoch+1}/{num_epochs}, step -> {i+1}/{n_iterations}, inputs -> {inputs.shape}")

epoch -> 1/2, step -> 1/45, inputs -> torch.Size([4, 13])
epoch -> 1/2, step -> 6/45, inputs -> torch.Size([4, 13])
epoch -> 1/2, step -> 11/45, inputs -> torch.Size([4, 13])
epoch -> 1/2, step -> 16/45, inputs -> torch.Size([4, 13])
epoch -> 1/2, step -> 21/45, inputs -> torch.Size([4, 13])
epoch -> 1/2, step -> 26/45, inputs -> torch.Size([4, 13])
epoch -> 1/2, step -> 31/45, inputs -> torch.Size([4, 13])
epoch -> 1/2, step -> 36/45, inputs -> torch.Size([4, 13])
epoch -> 1/2, step -> 41/45, inputs -> torch.Size([4, 13])
epoch -> 2/2, step -> 1/45, inputs -> torch.Size([4, 13])
epoch -> 2/2, step -> 6/45, inputs -> torch.Size([4, 13])
epoch -> 2/2, step -> 11/45, inputs -> torch.Size([4, 13])
epoch -> 2/2, step -> 16/45, inputs -> torch.Size([4, 13])
epoch -> 2/2, step -> 21/45, inputs -> torch.Size([4, 13])
epoch -> 2/2, step -> 26/45, inputs -> torch.Size([4, 13])
epoch -> 2/2, step -> 31/45, inputs -> torch.Size([4, 13])
epoch -> 2/2, step -> 36/45, inputs -> torch.Size([4, 13])
e